baseURL = "www.nsdmdh.com"
languageCode = "en-us"
title = "NSDMDH"

footnotereturnlinkcontents = "↩"
metaDataFormat = "yaml"
sectionPagesMenu = "main"

publishDir = "docs"

[outputs]
home = [ "HTML"]
