baseURL = "http://www.nsdmdh.com"
languageCode = "en-us"
title = "NSDMDH"

footnotereturnlinkcontents = "↩"
metaDataFormat = "yaml"
sectionPagesMenu = "main"

publishDir = "docs"

[outputs]
home = ["HTML"]

[params]
  image_path="/img/colours/cyan.png"
[blackfriday]
  fencedCode=true
