baseURL = "http://example.org/"
languageCode = "en-us"
title = "NSDMDH"
theme = "hugo-xmin"

footnotereturnlinkcontents = "↩"
languageCode = "en-us"
metaDataFormat = "yaml"

[outputs]
home = [ "HTML", "AMP"]
