baseURL = "localhost"
languageCode = "en-us"
title = "NSDMDH"
theme = "nevernever"

footnotereturnlinkcontents = "↩"
metaDataFormat = "yaml"
sectionPagesMenu = "main"

[outputs]
home = [ "HTML", "AMP"]
